[package]
name = "napi-rs-repor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features=["tokio_rt"] }
napi-derive = "2"

[build-dependencies]
napi-build = "1"
